POST http://localhost:5115/api/families/create_family/
Content-Type: application/json

{
  "familyName": "Михалковы",
  "adults": [{
    "name": "Иван",
    "phone": "+380631234567",
    "roleId": 2
  },
  {
    "name": "Мария",
    "phone": "+380632234567",
    "roleId": 1
  }
  ],
  "children": [{
    "name": "Паша",
    "birthDate": "02.10.2018",
    "roleId": 1
  },
  {
    "name": "Нина",
    "birthDate": "02.10.2018",
    "roleId": 2
  }]
}

###